apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels:
    release: {{ .Release.Name }}
data:
  application.conf: |-
    document.store {
      {{- if .Values.database }}
      {{- $dst := .Values.database.type }}
      dataStoreType = {{ $dst }}
      appName = {{ .Values.service.name }}

      {{- range $key, $value := (index .Values "database") }}
      {{- if ne $key $dst }}
      {{ $key }} = {{- toJson $value }}
      {{- end }}
      {{- end }}
    
      {{ $dst }} {
        {{- range $key, $value := (index .Values "database" (printf "%s" $dst)) }}
        {{- if $value }}
          {{- if hasPrefix "${?" (printf "%s" $value) }}
        {{ $key }} = {{ $value }}
          {{- else }}
        {{ $key }} = {{- toJson $value }}
          {{- end }}
        {{- end }}
        {{- end }}
      }
      {{- end }}
    }

    max.custom.attributes.per.tenant: {{ .Values.configMap.maxCustomAttributesPerTenant }}
