apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels:
    release: {{ .Release.Name }}
data:
  application.conf: |-
    document.store {
      {{- $dst := .Values.configMap.dataStoreType }}
      dataStoreType = {{ $dst }}
      appName = {{ .Values.service.name }}
      {{ $dst }} {
        {{- range $key, $value := (index .Values "configMap" (printf "%s" $dst)) }}
        {{- if $value }}
          {{- if hasPrefix "${?" (printf "%s" $value) }}
        {{ $key }} = {{ $value }}
          {{- else }}
            {{- if eq $key "endpoints" }}
        endpoints = {{- toJson $value }}
            {{- else }}
        {{ $key }} = {{ $value | quote }}
            {{- end }}
          {{- end }}
        {{- end }}
        {{- end }}
      }
    }

    max.custom.attributes.per.tenant: {{ .Values.configMap.maxCustomAttributesPerTenant }}
