name: 'Validate helm charts'
description: 'prevalidate helm chart template before its deployment; executes helm lint and helm template commands'
inputs:
  script:
    description: 'Customizable script run to install the opam package(s).'
    default: |
      helm dependency update ./helm/
      helm lint --strict ./helm/
      helm template ./helm/
runs:
  using: 'docker'
  image: 'hypertrace/helm-gcs-packager:0.3.1'
  args:
    - ${{ inputs.script }}
