name: 'Validate helm charts'
description: 'prevalidate helm chart template before its deployment; executes helm lint and helm template commands'
runs:
  using: "composite"
  steps: 
    - run: |
          helm dependency update ./helm/
          helm lint --strict ./helm/
          helm template ./helm/
      shell: bash
