FROM ghcr.io/openzipkin/alpine:3.12.1

# Use latest recommended version here
ARG HELM_VERSION=3.4.2

WORKDIR /usr/local/bin

# Install Helm, helm-gcs plugin, git and openssh-client
RUN apk --update --no-cache \
  curl https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz | tar xz \
  --strip=1 linux-amd64/helm && \
  helm plugin install https://github.com/hayorov/helm-gcs.git --version 0.3.6 && \
  apk del curl --purge && \
  rm -rf ~/.cache ~/.local/share/helm/plugins/helm-gcs.git/.git && \
  helm version && helm plugin list

ENV HELM_PLUGINS=/root/.local/share/helm/plugins

# Copies your code file from your action repository to the filesystem path `/` of the container
COPY entrypoint.sh /entrypoint.sh

# Code file to execute when the docker container starts up (`entrypoint.sh`)
ENTRYPOINT ["/entrypoint.sh"]
