name: 'Helm GCS Publish'
description: 'Published helm charts to GCS'
runs:
  using: "composite"
  steps: 
      run: |
          CHART_VERSION=$(echo ${GITHUB_REF} | cut -d/ -f 3)
          CHART_NAME=$(awk '/^name:/ {print $2}' ./helm/Chart.yaml)
          export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/helm-gcs-key.json
          echo $HELM_GCS_CREDENTIALS > ${GOOGLE_APPLICATION_CREDENTIALS}
          helm dependency update ./helm/
          helm repo add helm-gcs $HELM_GCS_REPOSITORY
          helm package --version ${CHART_VERSION} --app-version ${CHART_VERSION} ./helm/
          helm gcs push ${CHART_NAME}-${CHART_VERSION}.tgz helm-gcs --public --retry
      shell: bash




