###########
# Deployment and Service
###########
replicaCount: 1
maxUnavailable: 0

chartType: application

image:
  repository: hypertrace/attribute-service
  pullPolicy: IfNotPresent
  tagOverride: ""

imagePullSecrets: {}

containerPort: 9012
containerHealthProbePort: 9013

service:
  name: attribute-service
  type: ClusterIP
  port: 9012

nodeLabels: {}

tolerations: []

affinity: {}

topologySpreadConstraints: []

podSecurityContext: {}

containerSecurityContext: {}

commonPodLabels: {}

commonPodAnnotations: {}

javaOpts: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=75.0 -XX:MaxDirectMemorySize=128M -XX:+ExitOnOutOfMemoryError"

livenessProbe:
  periodSeconds: 5
  failureThreshold: 3
  timeoutSeconds: 3
startupProbe:
  periodSeconds: 5
  failureThreshold: 24
  timeoutSeconds: 3

resources:
  limits:
    cpu: 2
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 512Mi

deploymentLabels:
  app: attribute-service

podLabels:
  app: attribute-service

podAnnotations: {}

deploymentSelectorMatchLabels:
  app: attribute-service

serviceSelectorLabels:
  app: attribute-service

configMap:
  name: attribute-service-config
  maxCustomAttributesPerTenant: 5

logConfig:
  name: attribute-service-log-appender-config
  monitorInterval: 30
  rootLogger:
    level: INFO
  appender:
    rolling:
      enabled: false

config-bootstrapper:
  job:
    prefix: attribute
  configurationCommands: {}

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
