name: build
on:
  push:
    branches:
      - main
  pull_request_target:


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
       # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0
      
      - name: create checksum file
        run: find . -type f -name "*.gradle*" -o -name "gradle-wrapper*" | xargs shasum | sort > checksum.txt && cat checksum.txt

      - name: Cache packages
        id: cache-packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: gradle-packages-${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/checksum.txt') }}
          restore-keys: |
            gradle-packages-${{ runner.os }}-${{ github.job }}
            gradle-packages-${{ runner.os }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build with Gradle
        run: ./gradlew build dockerBuildImages

  validate-helm-charts:
    runs-on: ubuntu-20.04
    container: 
      image: hypertrace/helm-gcs-packager:0.3.0
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
     # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      - name: validate charts
        run: |
          helm dependency update ./helm/
          helm lint --strict ./helm/
          helm template ./helm/

  snyk-scan:
    runs-on: ubuntu-20.04
    steps:
    # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk11@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-sub-projects --policy-path=.snyk --configuration-matching='^runtimeClasspath$'
