name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
       # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      
      - name: create checksum file
        run: find . -type f -name "*.gradle*" -o -name "gradle-wrapper*" | xargs shasum | sort > checksum.txt && cat checksum.txt

      - name: Cache packages
        id: cache-packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: gradle-packages-${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/checksum.txt') }}
          restore-keys: |
            gradle-packages-${{ runner.os }}-${{ github.job }}
            gradle-packages-${{ runner.os }}

      - name: Unit test
        run: ./gradlew jacocoTestReport 

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.1.1
        with:
          fail_ci_if_error: true
          flags: unit

      - name: Integration test
        run: ./gradlew jacocoIntegrationTestReport 

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.1.1
        with:
          fail_ci_if_error: true
          flags: integration
