name: "test"

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: burrunan/gradle-cache-action@v1.6
        with:
          remote-build-cache-proxy-enabled: false
          arguments: --stacktrace 'jacocoTestReport'

      - uses: codecov/codecov-action@v1
        with:
          name: unit-test-report
          fail_ci_if_error: true
          flags: unit

      - uses: burrunan/gradle-cache-action@v1.6
        with:
          remote-build-cache-proxy-enabled: false
          arguments: --stacktrace 'jacocoIntegrationTestReport'
      - uses: codecov/codecov-action@v1
        with:
          name: integration-test-report
          fail_ci_if_error: true
          flags: integration

      - name: Copy test reports
        run: ./gradlew copyAllReports --output-dir=/tmp/test-reports

      - name: Archive test report
        uses: actions/upload-artifact@v1
        with:
          name: test-reports
          path: /tmp/test-reports
        if: ${{ always() }}