name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
       # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      
      - name: create checksum file
        uses: hypertrace/actions/checksum@main

      - name: Cache packages
        id: cache-packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: gradle-packages-${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/checksum.txt') }}
          restore-keys: |
            gradle-packages-${{ runner.os }}-${{ github.job }}
            gradle-packages-${{ runner.os }}

      - name: Unit test
        uses: ./.github/actions/gradle/
        with: 
          args: jacocoTestReport

      - name: Integration test
        uses: ./.github/actions/gradle/
        with: 
          args: jacocoIntegrationTestReport

      - name: validate charts
        uses: ./.github/actions/validate-charts/
