name: "test"

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: burrunan/gradle-cache-action@v1.6
        with:
          remote-build-cache-proxy-enabled: false
          arguments: --stacktrace 'jacocoTestReport'
      - uses: burrunan/gradle-cache-action@v1.6
        with:
          remote-build-cache-proxy-enabled: false
          arguments: --stacktrace 'jacocoIntegrationTestReport'
      - uses: codecov/codecov-action@v1