name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
       # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      
      - name: create checksum file
        run: find . -type f -name "*.gradle*" -o -name "gradle-wrapper*" | xargs shasum | sort > checksum.txt && cat checksum.txt

      - name: Unit test
        run: ./gradlew clean jacocoTestReport --stacktrace
        
      - name: Copy unit test reports
        run: ./gradlew copyAllReports --output-dir=/tmp/test-reports

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: codecov-line-smoothing
          fail_ci_if_error: true
          flags: unit

      - name: Integration test
        run: ./gradlew clean jacocoIntegrationTestReport --stacktrace

      - name: Copy integration test reports
        run: ./gradlew copyAllReports --output-dir=/tmp/test-reports


      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: codecov-line-smoothing
          fail_ci_if_error: true
          flags: integration

      - name: Archive integration test report
        uses: actions/upload-artifact@v1
        with:
          name: test-reports
          path: /tmp/test-reports
        if: ${{ always() }}
