name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
       # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      
      - name: create checksum file
        uses: hypertrace/actions/checksum@main

      - name: Cache packages
        id: cache-packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: gradle-packages-${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/checksum.txt') }}
          restore-keys: |
            gradle-packages-${{ runner.os }}-${{ github.job }}
            gradle-packages-${{ runner.os }}

      - name: Unit test
        run: ./gradlew jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: unit test reports
          fail_ci_if_error: true
          flags: unit

      - name: Integration test
        run: ./gradlew jacocoIntegrationTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: integration test reports
          fail_ci_if_error: true
          flags: integration

      - name: Copy test reports
        run: ./gradlew copyAllReports --output-dir=/tmp/test-reports

      - name: Archive test reports
        uses: actions/upload-artifact@v1
        with:
          name: test-reports
          path: /tmp/test-reports
        if: ${{ always() }}
  test-helm:
    runs-on: ubuntu-20.04
    container:
      image: hypertrace/helm-gcs-packager:0.3.1
      credentials:
        username: ${{ secrets.DOCKERHUB_READ_USER }}
        password: ${{ secrets.DOCKERHUB_READ_TOKEN }}
    steps:
      # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Test with env
        env:
          HELM_GCS_CREDENTIALS: DUMMY_CREDS_ENV
          HELM_GCS_REPOSITORY: gs://dummy_repo_env
        uses: ./.github/actions/helm-gcs-publish

      - name: Test with inputs
        uses: ./.github/actions/helm-gcs-publish
        with:
          helm-gcs-repository: gs://dummy_repo_input
          helm-gcs-credentials: DUMMY_CREDS_INPUT

      - name: Test with both
        env:
          HELM_GCS_CREDENTIALS: DUMMY_CREDS_ENV
          HELM_GCS_REPOSITORY: gs://dummy_repo_env
        uses: ./.github/actions/helm-gcs-publish
        with:
          helm-gcs-repository: gs://dummy_repo_input
          helm-gcs-credentials: DUMMY_CREDS_INPUT

      -