name: "PR Build"

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        include:
          - os: ubuntu-latest
            testAdditionalJavaVersions: true
            coverage: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: setup-java-8
        name: Setup Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jre
      - id: setup-java-11
        name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: burrunan/gradle-cache-action@v1.6
        with:
          remote-build-cache-proxy-enabled: false
          arguments: build --stacktrace ${{ matrix.coverage && 'jacocoTestReport' || '' }}
          properties: |
            testAdditionalJavaVersions=${{ matrix.testAdditionalJavaVersions }}
            org.gradle.java.installations.paths=${{ steps.setup-java-8.outputs.path }},${{ steps.setup-java-11.outputs.path }}
      - uses: codecov/codecov-action@v1
        if: ${{ matrix.coverage }}
      - uses: actions/upload-artifact@v2
        if: ${{ matrix.coverage }}
        with:
          name: coverage-report
          path: all/build/reports/jacoco/test/html