name: Publish Docker image
on:
# Will only run when release is published. 
  release:
    types: [published]
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    name: Build and run Docker images
    steps:
      - name: Update Packages
        run: sudo apt-get update -yqq --fix-missing

      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Cache gradle
        id: cache-gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: gradle-packages-${{ runner.os }}-${{ hashFiles('*.gradle*') }}

      - name: download dependencies
        run: ./gradlew downloadDependencies

      - name: Publish docker image
        run: ./gradlew publish dockerPushImages
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
