name: Publish helm charts
on:
  release:
    types: [published]

jobs:
  publish-helm-charts:
    runs-on: ubuntu-latest
    name: Build and run Docker images
    steps:
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          semver_only: true
      - name: package and release charts
        uses: WyriHaximus/github-action-helm3@v2
        run: |
            CHART_VERSION=${{ steps.get-latest-tag.outputs.tag }}
            CHART_NAME=$(awk '/^name:/ {print $2}' ./helm/Chart.yaml)
            export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/helm-gcs-key.json
            echo ${HELM_GCS_CREDENTIALS} > ${GOOGLE_APPLICATION_CREDENTIALS}
            helm dependency update ./helm/
            helm repo add helm-gcs ${HELM_GCS_REPOSITORY}
            helm package --version ${CHART_VERSION} --app-version ${CHART_VERSION} ./helm/
            helm gcs push ${CHART_NAME}-${CHART_VERSION}.tgz helm-gcs --public --retry
          

