name: Publish Docker image
on:
# Will only run when release is published. 
  push:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-images:
    runs-on: ubuntu-20.04
    steps:
      # Set fetch-depth: 0 to fetch all history for all branches and tags.
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: create checksum file
        run: find . -type f -name "*.gradle*" -o -name "gradle-wrapper*" | xargs shasum | sort > checksum.txt && cat checksum.txt

      - name: download dependencies
        run: ./gradlew downloadDependencies

      - name: Cache packages
        id: cache-packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          # reason to use CACHE_VERSION variable is to provide easy way to clear cache without commit. 
          # (Ref: https://github.community/t/how-to-clear-cache-in-github-actions/129038/5)
          key: gradle-packages-${{ runner.os }}-${{ github.head_ref }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/checksum.txt') }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish docker image
        run: ./gradlew publish dockerPushImages
