name: Publish Docker image
on:
# Will only run when release is published. 
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  publish-images:
    runs-on: ubuntu-20.04
    steps:
      - name: Update Packages
        run: sudo apt-get update -yqq --fix-missing

      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: create checksum file
        run: find . -type f -name "*.gradle*" -o -name "gradle-wrapper*" | xargs shasum | sort > checksum.txt && cat checksum.txt

      - name: Cache packages
        id: cache-packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: gradle-packages-${{ runner.os }}-${{ github.head_ref }}-${{ hashFiles('**/checksum.txt') }}

      - name: download dependencies
        run: ./gradlew downloadDependencies

      - name: docker login
        run: echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish docker image
        run: ./gradlew publish dockerPushImages
