# this is WIP and needs a revision and testing before merging. Also we need to add this secrets in GH secrets
name: Publish helm charts
on:
# Will only run when release is published. 
  release:
    types: [published]

jobs:
  publish-helm-charts:
    runs-on: ubuntu-latest
    container: hypertrace/helm-gcs-packager:0.3.0
    name: Build and run Docker images
    steps:
      - name: package and release charts
        env:
          CHART_VERSION=$(echo ${GITHUB_REF} | cut -d/ -f 3) # GITHUB_REF will be refs/tags/docker-MAJOR.MINOR.PATCH
          CHART_NAME=$(awk '/^name:/ {print $2}' ./helm/Chart.yaml)
          HELM_GCS_REPOSITORY=${{ secrets.HELM_GCS_REPOSITORY }}
        run: |
            export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/helm-gcs-key.json
            echo ${HELM_GCS_CREDENTIALS} > ${GOOGLE_APPLICATION_CREDENTIALS}
            helm dependency update ./helm/
            helm repo add helm-gcs "$HELM_GCS_REPOSITORY"
            helm package --version ${CHART_VERSION} --app-version ${CHART_VERSION} ./helm/
            helm gcs push ${CHART_NAME}-${CHART_VERSION}.tgz helm-gcs --public --retry



