name: snyk for gradle
on:
  push:
    branches:
      - main
  release:
    types: # This configuration does not affect the page_build event above
      - created
  pull_request_target:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/gradle-jdk11@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --all-sub-projects --policy-path=.snyk --configuration-matching='^runtimeClasspath$'