name: snyk for gradle
on: 
  push:
  pull_request_target:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/gradle@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --all-sub-projects --policy-path=.snyk --configuration-matching='^runtimeClasspath$'