name: validate charts
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  validate-helm-charts:
    runs-on: ubuntu-20.04
    container: hypertrace/helm-gcs-packager:0.3.0
    # Set fetch-depth: 0 to fetch all history for all branches and tags.
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 2

      - name: validate charts
        run: |
          helm dependency update ./helm/
          helm lint --strict ./helm/
          helm template ./helm/
        