name: validate charts
on:
  push:
    branches:
      - main
  pull_request:


jobs:
  validate-helm-charts:
    runs-on: ubuntu-20.04
    container: 
    image: hypertrace/helm-gcs-packager:0.3.0
    credentials:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
     # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: validate charts
        run: |
          helm dependency update ./helm/
          helm lint --strict ./helm/
          helm template ./helm/
        